export const GET_WEATHER = "GET_WEATHER";
export const FILTER_CITIES = "UPDATE_CITIES";
export const DELETE_CITY = "DELETE_CITY";
export const GET_WEATHER_DATA_ERROR = "GET_WEATHER_DATA_ERROR";
export const UPDATE_WEATHER = "UPDATE_WEATHER";
